# Generated by Django 2.2.6 on 2019-10-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20191025_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
