# Generated by Django 2.2.6 on 2019-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateRental',
            new_name='RentalDate',
        ),
        migrations.AddField(
            model_name='book',
            name='client_email',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='book',
            name='client_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
