# Generated by Django 2.2.6 on 2019-10-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20191031_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name_plural': 'Hosts'},
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='ownership',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
