# Generated by Django 2.2.6 on 2019-10-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20191031_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='amount_pax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ownership',
            name='title',
            field=models.CharField(default='Undefined Title', max_length=60),
        ),
    ]
