# Generated by Django 2.2.6 on 2019-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_ownership_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
