# Generated by Django 2.2.6 on 2019-11-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20191103_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
