# Generated by Django 2.2.6 on 2019-11-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20191104_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
