# Generated by Django 2.2.6 on 2019-11-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20191104_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='cover',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
