# Generated by Django 2.2.6 on 2019-11-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20191104_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Host'),
        ),
    ]
