# Generated by Django 2.2.6 on 2019-11-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_ownership_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='cover',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
    ]
