# Generated by Django 2.2.6 on 2019-11-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20191107_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='client_lastname',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='rentaldate',
            name='booked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Book'),
        ),
        migrations.AlterField(
            model_name='rentaldate',
            name='ownership',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Ownership'),
        ),
    ]
