# Generated by Django 2.2.6 on 2019-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_auto_20191113_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='description',
            field=models.TextField(default='', max_length=3000, null=True),
        ),
    ]
