# Generated by Django 2.2.6 on 2019-11-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20191113_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldate',
            name='date',
            field=models.DateField(),
        ),
    ]
