# Generated by Django 2.2.6 on 2019-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_auto_20191113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
